"""Static MASTER_ADMIN control matrix registry (source of truth).

Derived from the Backend + Edge Discovery Audit and the-eye-terminal-architecture.md.
Update this file when capabilities ship or edge routes change.
"""

from __future__ import annotations

from datetime import UTC, datetime

from zinc_schemas.admin_dto import (
    ControlMatrixCategorySummary,
    ControlMatrixEntry,
    ControlMatrixResponse,
)

MATRIX_VERSION = "2026-06-24.14"


def _entry(
    *,
    id: str,
    title: str,
    category: str,
    role_required: str = "operator",
    viewable: bool = False,
    controllable: bool = False,
    editable: bool = False,
    schedulable: bool = False,
    kill_switch: bool = False,
    dangerous: bool = False,
    confirmation_required: bool = False,
    audit_required: bool = False,
    audit_implemented: bool = False,
    priority: str = "Medium",
    backend_source: str | None = None,
    frontend_location: str | None = None,
    api_route: str | None = None,
    backend_gap: str | None = None,
    frontend_gap: str | None = None,
    backend_only_reason: str | None = None,
    cloudflare_dependency: str | None = None,
    service_port_dependency: str | None = None,
    trusted_host_dependency: bool = False,
    health_endpoint: str | None = None,
    notes: str | None = None,
) -> ControlMatrixEntry:
    """Construct a matrix row with dangerous-action defaults applied."""
    if dangerous:
        confirmation_required = True
        audit_required = True
    return ControlMatrixEntry(
        id=id,
        title=title,
        category=category,
        backend_source=backend_source,
        frontend_location=frontend_location,
        api_route=api_route,
        role_required=role_required,
        viewable=viewable,
        controllable=controllable,
        editable=editable,
        schedulable=schedulable,
        kill_switch=kill_switch,
        dangerous=dangerous,
        confirmation_required=confirmation_required,
        audit_required=audit_required,
        audit_implemented=audit_implemented,
        backend_gap=backend_gap,
        frontend_gap=frontend_gap,
        backend_only_reason=backend_only_reason,
        cloudflare_dependency=cloudflare_dependency,
        service_port_dependency=service_port_dependency,
        trusted_host_dependency=trusted_host_dependency,
        health_endpoint=health_endpoint,
        priority=priority,
        notes=notes,
    )


def _edge_routes() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="edge.route.dataapi-theeyebeta-store",
            title="dataapi.theeyebeta.store",
            category="Cloudflare/Edge",
            backend_source="TheEyeBetaDataAPI/deploy/cloudflared-config.yml",
            frontend_location="/admin/edge",
            api_route="GET /admin/edge/routes",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            cloudflare_dependency="dataapi.theeyebeta.store",
            service_port_dependency="127.0.0.1:7000",
            trusted_host_dependency=True,
            health_endpoint="/health",
            notes="Canonical Data API public hostname.",
        ),
        _entry(
            id="edge.route.dataapiprod-theeyebeta-store",
            title="dataapiprod.theeyebeta.store",
            category="Cloudflare/Edge",
            backend_source="TheEyeBetaDataAPI/deploy/cloudflared-config.yml",
            frontend_location="/admin/edge",
            api_route="GET /admin/edge/routes",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="High",
            cloudflare_dependency="dataapiprod.theeyebeta.store",
            service_port_dependency="127.0.0.1:7000",
            trusted_host_dependency=True,
            health_endpoint="/health",
            notes="Shared backend with dataapi.theeyebeta.store on :7000 (intentional until split).",
        ),
        _entry(
            id="edge.route.api-theeyebeta-store",
            title="api.theeyebeta.store",
            category="Cloudflare/Edge",
            backend_source="TheEyeBetaDataAPI/deploy/cloudflared-config.yml",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="High",
            cloudflare_dependency="api.theeyebeta.store",
            service_port_dependency="127.0.0.1:8000",
            health_endpoint="/health",
            notes="TheEyeBetaLocal Main API.",
        ),
        _entry(
            id="edge.route.admin-theeyebeta-store",
            title="admin.theeyebeta.store",
            category="Cloudflare/Edge",
            backend_source="TheEyeBetaDataAPI/deploy/cloudflared-config.yml",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="High",
            cloudflare_dependency="admin.theeyebeta.store",
            service_port_dependency="127.0.0.1:7200",
            health_endpoint="/admin/health",
            notes="The Eye Terminal (admin_service).",
        ),
        _entry(
            id="edge.drift.tunnel-port-mismatch",
            title="Tunnel port drift detection",
            category="Cloudflare/Edge",
            backend_source="admin_service/edge/drift_checker.py",
            frontend_location="/admin/edge",
            api_route="GET /admin/edge/routes/drift",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            cloudflare_dependency="cloudflared tunnel ingress",
            notes="Detects tunnel target port ≠ registered port (e.g. :9500 vs :7000).",
        ),
        _entry(
            id="edge.drift.trusted-host-missing",
            title="Trusted host allowlist detection",
            category="Trusted Hosts",
            backend_source="TheEyeBetaDataAPI/app/core/config.py (TRUSTED_HOSTS)",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=False,
            priority="Critical",
            trusted_host_dependency=True,
            backend_gap=(
                "Runtime TRUSTED_HOSTS compared via GET /admin/edge/trusted-hosts; "
                "runtime .env values are not returned (hostname lists only)."
            ),
            notes="Hostname in tunnel must appear in TRUSTED_HOSTS or Data API returns 400.",
        ),
        _entry(
            id="edge.drift.port-service-mismatch",
            title="Port / service mismatch detection",
            category="Service Port Registry",
            backend_source="control_matrix/registry.py + systemd unit map",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=False,
            priority="Critical",
            backend_gap=(
                "Live port/health probes run via GET /admin/edge/routes/drift and "
                "POST /admin/edge/routes/check; requires host access from admin_service."
            ),
            notes="Detects nothing listening on registered tunnel target port.",
        ),
        _entry(
            id="edge.sync.cloudflare-remote-ingress",
            title="Cloudflare remote ingress sync",
            category="Cloudflare/Edge",
            backend_source="TheEyeBetaDataAPI/scripts/sync_tunnel.sh",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=False,
            dangerous=True,
            audit_implemented=False,
            priority="Critical",
            cloudflare_dependency="Cloudflare Tunnel API (sync_tunnel.sh)",
            backend_gap="No guarded Terminal workflow; CLI/sudo only today.",
            frontend_gap="No operator UI for sync status or guarded trigger.",
            backend_only_reason="Mutates remote Cloudflare ingress; requires sudo/CF credentials outside UI.",
            notes="Never expose CF API tokens in Terminal.",
        ),
        _entry(
            id="cloudflare.status.module",
            title="Cloudflare edge status",
            category="Cloudflare/Edge",
            backend_source="admin_service/edge/cloudflare_client.py",
            frontend_location="/admin/edge",
            api_route="GET /admin/cloudflare/status",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="High",
            notes="Local/dummy mode when CLOUDFLARE_API_TOKEN absent; credentials presence only.",
        ),
    ]


def _edge_registry_and_ports() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="edge.registry.module",
            title="Edge Route Registry",
            category="Edge Route Registry",
            backend_source="admin_service/edge/service.py",
            frontend_location="/admin/edge",
            api_route="GET /admin/edge/routes",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            notes="Live drift probes + route registry API.",
        ),
        _entry(
            id="edge.data-api.public-routing",
            title="Data API public routing control",
            category="Data API public routing",
            backend_source="TheEyeBetaDataAPI/app/main.py + deploy/cloudflared-config.yml",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            service_port_dependency="127.0.0.1:7000",
            trusted_host_dependency=True,
            health_endpoint="/health",
            frontend_gap="Data API health not on dashboard; admin routes not integrated.",
        ),
        _entry(
            id="trusted-hosts.dataapi-theeyebeta-store",
            title="TRUSTED_HOSTS: dataapi.theeyebeta.store",
            category="Trusted Hosts",
            backend_source="TheEyeBetaDataAPI/.env.example TRUSTED_HOSTS",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            editable=True,
            priority="High",
            trusted_host_dependency=True,
            backend_gap="Runtime .env not readable from Terminal (by design — no secret exposure).",
            notes="Listed in committed .env.example.",
        ),
        _entry(
            id="trusted-hosts.dataapiprod-theeyebeta-store",
            title="TRUSTED_HOSTS: dataapiprod.theeyebeta.store",
            category="Trusted Hosts",
            backend_source="TheEyeBetaDataAPI/.env.example TRUSTED_HOSTS",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            editable=True,
            priority="High",
            trusted_host_dependency=True,
            backend_gap="Runtime .env not readable from Terminal (by design — no secret exposure).",
            notes="Listed in committed .env.example; required or API returns 400 Invalid host header.",
        ),
        _entry(
            id="port.registry.data-api-7000",
            title="Data API service port 7000",
            category="Service Port Registry",
            backend_source="TheEyeBetaDataAPI/app/core/config.py API_PORT=7000",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            service_port_dependency="127.0.0.1:7000",
            health_endpoint="/health",
            notes="theeyebeta-dataapi.service via scripts/install_service.sh",
        ),
        _entry(
            id="edge.port.sentinel-unregistered-9500",
            title="Unregistered port 9500 (incident sentinel)",
            category="Service Port Registry",
            backend_source="Incident record: dataapiprod :9500 misroute",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            service_port_dependency="127.0.0.1:9500",
            backend_only_reason=(
                "Port 9500 is NOT an expected service target. "
                "Tunnel routing here indicates Critical drift (502). "
                "Do not register as production unless explicitly approved."
            ),
            notes="Explicit sentinel — not a valid Data API port.",
        ),
    ]


def _command_center_and_master_admin() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="command.dashboard",
            title="Operator dashboard",
            category="Command Center",
            backend_source="admin_service/api/views.py",
            frontend_location="/admin/",
            api_route="GET /admin/fragments/stats",
            viewable=True,
            controllable=False,
            priority="Medium",
        ),
        _entry(
            id="command.verify-audit-chain",
            title="Verify audit chain (quick action)",
            category="Command Center",
            backend_source="admin_service/api/views.py",
            frontend_location="/admin/",
            api_route="POST /admin/actions/verify-audit-chain",
            viewable=True,
            controllable=True,
            priority="Low",
            audit_implemented=True,
        ),
        _entry(
            id="command.run-daily-backtest",
            title="Run daily backtest (quick action)",
            category="Command Center",
            backend_source="admin_service/api/views.py",
            frontend_location="/admin/",
            api_route="POST /admin/actions/run-daily-backtest",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="master-admin.control-matrix",
            title="MASTER_ADMIN control matrix",
            category="MASTER_ADMIN",
            backend_source="admin_service/control_matrix/registry.py",
            frontend_location="/admin/master-admin",
            api_route="GET /admin/master-admin/control-matrix",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            notes="This registry — source of truth for parity. "
            "Staleness checks: control_matrix/staleness.py (static expected_registry). "
            "Future: dynamic FastAPI route discovery.",
        ),
        _entry(
            id="master-admin.rbac",
            title="RBAC / MASTER_ADMIN role enforcement",
            category="MASTER_ADMIN",
            backend_source="admin_service/rbac.py + users/service.py",
            frontend_location="/admin/users",
            api_route="GET /admin/users",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="JWT roles claim issued on login; MASTER_ADMIN required for user mutations.",
        ),
        _entry(
            id="admin.users.control-plane",
            title="Users / Permissions control plane",
            category="MASTER_ADMIN",
            backend_source="admin_service/api/users.py",
            frontend_location="/admin/users",
            api_route="GET /admin/users",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
    ]


def _admin_pages() -> list[ControlMatrixEntry]:
    pages: list[tuple[str, str, str, str, str, str]] = [
        ("orders", "Pending orders", "Orders/OMS", "admin_service/api/orders.py", "/admin/orders", "GET /admin/orders/pending"),
        ("audit", "Audit log", "Audit", "admin_service/api/audit.py", "/admin/audit", "GET /admin/audit/log"),
        ("agents", "Agents", "Agents", "admin_service/api/agents.py", "/admin/agents", "GET /admin/agents"),
        ("violations", "Guard violations", "Legal/Compliance", "admin_service/api/guard.py", "/admin/violations", "GET /admin/guard/violations"),
        ("costs", "Costs", "Costs", "admin_service/api/costs.py", "/admin/costs", "GET /admin/costs/daily"),
        ("sql", "SQL playground", "Database", "admin_service/api/sql.py", "/admin/sql", "POST /admin/sql/query"),
        ("proposals", "Proposals", "Proposals/Signals", "admin_service/api/proposals.py", "/admin/proposals", "GET /admin/proposals"),
    ]
    return [
        _entry(
            id=f"admin.page.{key}",
            title=title,
            category=category,
            backend_source=src,
            frontend_location=loc,
            api_route=route,
            viewable=True,
            controllable=False,
            priority="Medium",
        )
        for key, title, category, src, loc, route in pages
    ]


def _dangerous_admin_actions() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.action.approve-order",
            title="Approve order",
            category="Orders/OMS",
            backend_source="admin_service/api/orders.py",
            frontend_location="/admin/orders",
            api_route="POST /admin/orders/{id}/approve",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="admin.action.reject-order",
            title="Reject order",
            category="Orders/OMS",
            backend_source="admin_service/api/orders.py",
            frontend_location="/admin/orders",
            api_route="POST /admin/orders/{id}/reject",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="admin.action.sql-execute",
            title="SQL write execute",
            category="Database",
            backend_source="admin_service/api/sql.py",
            frontend_location="/admin/sql",
            api_route="POST /admin/sql/execute",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="admin.action.restart-service",
            title="Restart whitelisted systemd service",
            category="Services/systemd",
            backend_source="admin_service/api/services.py",
            frontend_location="/admin/services",
            api_route="POST /admin/services/{name}/restart",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="admin.action.approve-proposal",
            title="Approve proposal",
            category="Proposals/Signals",
            backend_source="admin_service/api/proposals.py",
            frontend_location="/admin/proposals",
            api_route="POST /admin/proposals/{id}/approve",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="admin.action.run-agent",
            title="Trigger agent run",
            category="Agents",
            backend_source="admin_service/api/agents.py",
            frontend_location="/admin/agents",
            api_route="POST /admin/agents/{id}/run",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="admin.action.resolve-violation",
            title="Resolve guard violation",
            category="Legal/Compliance",
            backend_source="admin_service/api/guard.py",
            frontend_location="/admin/violations",
            api_route="POST /admin/guard/violations/{id}/resolve",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Medium",
        ),
        _entry(
            id="admin.action.start-backtest",
            title="Start backtest",
            category="Backtests",
            backend_source="admin_service/api/backtest.py",
            frontend_location=None,
            api_route="POST /admin/backtest",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
            frontend_gap="No /backtests HTML page.",
        ),
    ]


def _services_systemd() -> list[ControlMatrixEntry]:
    units = [
        ("admin-service", "theeyebeta-admin", "7200", "TheEyeProd/infra/systemd/theeyebeta-admin.service"),
        ("data-api", "theeyebeta-dataapi", "7000", "TheEyeBetaDataAPI/scripts/install_service.sh"),
        ("local-api", "theeyebeta-api", "8000", "TheEyeBetaLocal/scripts/systemd/theeyebeta-api.service"),
        ("local-engine", "theeyebeta-engine", None, "TheEyeBetaLocal/scripts/systemd/theeyebeta-engine.service"),
        ("local-trask", "theeyebeta-trask", "8090", "TheEyeBetaLocal/scripts/systemd/theeyebeta-trask.service"),
        ("llm-gateway", "theeyebeta-litellm", "7020", "Referenced in api/services.py — unit not in repo"),
        ("nats", "nats", None, "Infrastructure"),
        ("redis", "redis-server", None, "Infrastructure"),
        ("cloudflared", "cloudflared", None, "Host /etc/cloudflared/config.yml"),
    ]
    rows: list[ControlMatrixEntry] = []
    for name, unit, port, src in units:
        port_dep = f"127.0.0.1:{port}" if port else None
        restartable = name in {
            "admin-service",
            "data-api",
            "llm-gateway",
            "cloudflared",
            "local-api",
            "local-trask",
        }
        rows.append(
            _entry(
                id=f"service.systemd.{name}",
                title=f"systemd: {unit}",
                category="Services/systemd",
                backend_source=src,
                frontend_location="/admin/services",
                api_route=f"GET /admin/services/{name}",
                viewable=True,
                controllable=restartable,
                dangerous=restartable or name in {"data-api", "admin-service", "cloudflared"},
                audit_implemented=True,
                priority="Critical" if name in {"data-api", "cloudflared"} else "High" if name == "admin-service" else "Medium",
                service_port_dependency=port_dep,
                health_endpoint="/health" if port else None,
                backend_gap="Unit file not committed" if "not in repo" in src else None,
                cloudflare_dependency="cloudflared" if name == "cloudflared" else None,
                notes="Allowlisted in services_control/registry.py" if name == "data-api" else None,
            ),
        )
    rows.append(
        _entry(
            id="admin.services.control-plane",
            title="Services / systemd control plane",
            category="Services/systemd",
            backend_source="admin_service/api/services.py + services_control/",
            frontend_location="/admin/services",
            api_route="GET /admin/services",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Port ownership at GET /admin/services/ports; stop/disable critical units need MASTER_ADMIN.",
        ),
    )
    return rows


def _workers_timers() -> list[ControlMatrixEntry]:
    workers = [
        ("gap-sentinel", "theeye-gap-sentinel", "Mon-Fri 07:30 UTC", "workers/gap_sentinel_worker.py"),
        ("macro", "theeye-macro", "Mon-Fri 21:20 UTC", "workers/macro_pipeline.py"),
        ("massive-ingest", "theeye-massive-ingest", "Mon-Fri 21:30 UTC", "workers/massive_ingestion_worker.py"),
        ("daily-pipeline", "theeye-daily-pipeline", "Mon-Fri 21:35 UTC", "workers/daily_pipeline_runner.py"),
        ("sector", "theeye-sector", "Mon-Fri 22:05 UTC", "workers/sector_aggregation_worker.py"),
        ("supabase-sync", "theeye-supabase-sync", "Mon-Fri 22:20 UTC", "workers/supabase_sync_worker.py"),
        ("intraday-ingest", "theeye-intraday-ingest", "Mon-Fri */15 min", "workers/intraday_ingestion_worker.py"),
        ("backup", "theeye-backup", "Daily 02:00 UTC", "scripts/backup_db.sh"),
        ("local-daily", "theeyebeta-daily", "Mon-Fri 18:00", "TheEyeBetaLocal/scripts/systemd/theeyebeta-daily.timer"),
    ]
    return [
        _entry(
            id=f"worker.{key}",
            title=f"Worker timer: {unit}",
            category="Workers/Schedulers",
            backend_source=f"TheEyeProd/{src}",
            frontend_location="/admin/workers",
            api_route=f"GET /admin/workers/{key}",
            schedulable=True,
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High" if key in {"gap-sentinel", "intraday-ingest", "massive-ingest"} else "Medium",
            notes=f"Schedule: {schedule}. Control gaps surfaced in Workers panel.",
        )
        for key, unit, schedule, src in workers
    ] + [
        _entry(
            id="admin.workers.control-plane",
            title="Workers / Schedulers control plane",
            category="Workers/Schedulers",
            backend_source="admin_service/api/workers.py + api/timers.py",
            frontend_location="/admin/workers",
            api_route="GET /admin/workers",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Operators read registry; MASTER_ADMIN + confirm for force run, stop, timer disable, schedule/config edits.",
        ),
    ]


def _emergency_trading() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.trading.control-plane",
            title="Emergency Trading control plane",
            category="Emergency Trading",
            backend_source="admin_service/api/trading.py + trading_control/",
            frontend_location="/admin/emergency",
            api_route="GET /admin/trading/status",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Live enable requires token + confirm; halt clears live; resume does not auto-enable live.",
        ),
        _entry(
            id="trading.live-approval",
            title="Enable live trading (token + DB approval)",
            category="Emergency Trading",
            backend_source="trading_control/service.py + broker live_gate.py",
            frontend_location="/admin/emergency",
            api_route="POST /admin/trading/live-approval",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="trading.emergency-halt",
            title="Emergency trading halt",
            category="Emergency Trading",
            backend_source="trading_control/service.py + oms/submission_gate.py",
            frontend_location="/admin/emergency",
            api_route="POST /admin/trading/emergency-halt",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="trading.resume-from-halt",
            title="Resume from emergency halt",
            category="Emergency Trading",
            backend_source="trading_control/service.py",
            frontend_location="/admin/emergency",
            api_route="POST /admin/trading/resume-from-halt",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Does not silently re-enable live trading.",
        ),
        _entry(
            id="trading.oms-submission-gate",
            title="OMS submission gate",
            category="Emergency Trading",
            backend_source="services/oms/submission_gate.py",
            frontend_location="/admin/emergency",
            api_route="GET /admin/trading/status",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            service_port_dependency="127.0.0.1:7080",
        ),
        _entry(
            id="trading.broker-live-gate",
            title="Broker live trading gate",
            category="Emergency Trading",
            backend_source="services/broker_adapter_alpaca/live_gate.py",
            frontend_location="/admin/emergency",
            api_route="GET /admin/trading/status",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            service_port_dependency="127.0.0.1:7090",
        ),
    ]


def _risk_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.risk.control-plane",
            title="Risk cockpit control plane",
            category="Risk",
            backend_source="admin_service/api/risk.py + risk_control/",
            frontend_location="/admin/risk",
            api_route="GET /admin/risk/status",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Operators supervise metrics/breaches; MASTER_ADMIN + confirm for compute, override, limits, trading lock.",
        ),
        _entry(
            id="risk.compute",
            title="Force risk metrics recompute",
            category="Risk",
            backend_source="risk_control/service.py + risk_service HTTP :8007",
            frontend_location="/admin/risk",
            api_route="POST /admin/risk/compute",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="risk.override",
            title="Override risk block",
            category="Risk",
            backend_source="risk_control/service.py",
            frontend_location="/admin/risk",
            api_route="POST /admin/risk/override",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Requires reason + X-Confirm; recorded in admin_risk_overrides and audit log.",
        ),
        _entry(
            id="risk.limits.patch",
            title="Edit risk limits overlay",
            category="Risk",
            backend_source="risk_control/repository.py",
            frontend_location="/admin/risk",
            api_route="PATCH /admin/risk/limits",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Persists admin_risk_limits; validator still reads portfolios.mandate until wired.",
        ),
        _entry(
            id="risk.trading-lock",
            title="Risk trading lock / unlock",
            category="Risk",
            backend_source="risk_control/service.py",
            frontend_location="/admin/risk",
            api_route="POST /admin/risk/trading-lock",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Advisory lock in admin_risk_state; use Emergency Trading halt for production stops.",
        ),
    ]


def _compliance_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.compliance.control-plane",
            title="Legal/Compliance cockpit control plane",
            category="Legal/Compliance",
            backend_source="admin_service/api/compliance.py + compliance_control/",
            frontend_location="/admin/compliance",
            api_route="GET /admin/compliance/status",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Operators supervise checks/rules; MASTER_ADMIN + confirm for recheck, override, rules, exceptions, legal hold.",
        ),
        _entry(
            id="compliance.recheck",
            title="Force compliance order recheck",
            category="Legal/Compliance",
            backend_source="compliance_control/service.py + compliance_service HTTP :8008",
            frontend_location="/admin/compliance",
            api_route="POST /admin/compliance/checks/recheck",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="compliance.override",
            title="Override compliance block",
            category="Legal/Compliance",
            backend_source="compliance_control/service.py",
            frontend_location="/admin/compliance",
            api_route="POST /admin/compliance/override",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Requires reason + X-Confirm; enforcement gap until wired into compliance_service.",
        ),
        _entry(
            id="compliance.rules.patch",
            title="Edit compliance rules overlay",
            category="Legal/Compliance",
            backend_source="compliance_control/repository.py",
            frontend_location="/admin/compliance",
            api_route="PATCH /admin/compliance/rules",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Persists admin_compliance_rules; engine still reads portfolios.mandate until wired.",
        ),
        _entry(
            id="compliance.exception.create",
            title="Create compliance exception",
            category="Legal/Compliance",
            backend_source="compliance_control/service.py",
            frontend_location="/admin/compliance",
            api_route="POST /admin/compliance/exceptions",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="compliance.legal-hold",
            title="Apply or release legal hold",
            category="Legal/Compliance",
            backend_source="compliance_control/service.py",
            frontend_location="/admin/compliance",
            api_route="POST /admin/compliance/legal-hold",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Recorded in admin_legal_holds; order flow enforcement not wired yet.",
        ),
    ]


def _orders_blotter() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.orders.blotter",
            title="Orders / OMS blotter",
            category="Orders/OMS",
            backend_source="admin_service/api/orders.py + blotter_control/",
            frontend_location="/admin/orders",
            api_route="GET /admin/orders",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Full lifecycle visibility; MASTER_ADMIN + confirm for approve/cancel/replace.",
        ),
        _entry(
            id="orders.cancel",
            title="Cancel live order",
            category="Orders/OMS",
            backend_source="blotter_control/service.py",
            frontend_location="/admin/orders",
            api_route="POST /admin/orders/{id}/cancel",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="orders.replace",
            title="Replace live order",
            category="Orders/OMS",
            backend_source="blotter_control/service.py",
            frontend_location="/admin/orders",
            api_route="POST /admin/orders/{id}/replace",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
    ]


def _broker_blotter() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.broker.blotter",
            title="Broker / Portfolio blotter",
            category="Broker/Portfolio",
            backend_source="admin_service/api/broker.py + blotter_control/",
            frontend_location="/admin/broker",
            api_route="GET /admin/broker/status",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            notes="Positions, fills, broker drift; test-connection requires MASTER_ADMIN.",
        ),
        _entry(
            id="broker.test-connection",
            title="Broker test connection",
            category="Broker/Portfolio",
            backend_source="blotter_control/client.py",
            frontend_location="/admin/broker",
            api_route="POST /admin/broker/test-connection",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="oms.reconciliation.resolve",
            title="Resolve OMS reconciliation pause",
            category="Orders/OMS",
            backend_source="blotter_control/service.py + services/oms/app.py",
            frontend_location="/admin/broker",
            api_route="POST /admin/oms/reconciliation/resolve",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Requires reason + confirm; cannot blindly clear drift.",
        ),
    ]


def _market_data_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.market-data.status",
            title="Market data quality cockpit",
            category="Market Data",
            backend_source="market_control/service.py + api/market_data.py",
            frontend_location="/admin/market-data",
            api_route="GET /admin/market-data/status",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Critical",
            notes="Freshness, gaps, providers, Data API internal + public route health.",
        ),
        _entry(
            id="market.gap.resolve",
            title="Mark data gap resolved",
            category="Market Data",
            backend_source="market_control/repository.py",
            frontend_location="/admin/market-data",
            api_route="POST /admin/market-data/gaps/{id}/resolve",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
            notes="Updates public.audit_data_gaps remediation_state to RESOLVED.",
        ),
        _entry(
            id="market.backfill",
            title="Trigger data backfill",
            category="Market Data",
            backend_source="market_control/client.py",
            frontend_location="/admin/market-data",
            api_route="POST /admin/market-data/backfill",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Proxies data-ingestion POST /ingest/run; Basic auth gap documented.",
        ),
    ]


def _snapshots_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.snapshots.list",
            title="Snapshot packager visibility",
            category="Market Data",
            backend_source="market_control/service.py + api/snapshots.py",
            frontend_location="/admin/snapshots",
            api_route="GET /admin/snapshots",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="High",
        ),
        _entry(
            id="snapshot.build",
            title="Rebuild packaged snapshot",
            category="Market Data",
            backend_source="market_control/client.py",
            frontend_location="/admin/snapshots",
            api_route="POST /admin/snapshots/build",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
    ]


def _sector_universe_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.sectors.rotation",
            title="Sector rotation rank",
            category="Market Data",
            backend_source="sector_control/service.py + api/sectors.py",
            frontend_location="/admin/sectors/rotation",
            api_route="GET /admin/sectors/rotation",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Medium",
            notes="rotation_rank and relative strength from theeyebeta.sector_daily.",
        ),
        _entry(
            id="admin.sectors.breadth",
            title="Sector breadth",
            category="Market Data",
            backend_source="sector_control/service.py + api/sectors.py",
            frontend_location="/admin/sectors/breadth",
            api_route="GET /admin/sectors/breadth",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Medium",
            notes="% above SMA50/SMA200 and median RSI from theeyebeta.sector_daily.",
        ),
        _entry(
            id="admin.sectors.performance",
            title="Sector performance history",
            category="Market Data",
            backend_source="sector_control/service.py + api/sectors.py",
            frontend_location="/admin/sectors/performance",
            api_route="GET /admin/sectors/performance",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Medium",
            notes="1d/5d/30d sector return history from theeyebeta.sector_daily.",
        ),
        _entry(
            id="admin.universe.caps",
            title="Universe cap rank",
            category="Market Data",
            backend_source="universe_control/service.py + api/universe.py",
            frontend_location="/admin/universe/caps",
            api_route="GET /admin/universe/caps",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Medium",
            notes="$500M+ cap-ranked active universe from theeyebeta.market_cap_daily.",
        ),
        _entry(
            id="admin.universe.churn",
            title="Universe churn",
            category="Market Data",
            backend_source="universe_control/service.py + api/universe.py",
            frontend_location="/admin/universe/churn",
            api_route="GET /admin/universe/churn",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="Medium",
            notes="New entrants/dropouts from theeyebeta.audit_cap_events.",
        ),
    ]


def _intelligence_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.agents.detail",
            title="Agents registry and control",
            category="Agents",
            backend_source="intelligence_control/service.py + api/agents.py",
            frontend_location="/admin/agents",
            api_route="GET /admin/agents/{id}",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="agent.run",
            title="Run expensive agent",
            category="Agents",
            backend_source="api/agents.py + agent-runtime",
            frontend_location="/admin/agents",
            api_route="POST /admin/agents/{id}/run",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            kill_switch=True,
            priority="Critical",
        ),
        _entry(
            id="admin.proposals.actions",
            title="Proposal approve/reject/defer/supersede/rollback",
            category="Proposals/Signals",
            backend_source="intelligence_control/service.py + api/proposals.py",
            frontend_location="/admin/proposals",
            api_route="POST /admin/proposals/{id}/approve",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="admin.backtests.cockpit",
            title="Backtests control plane",
            category="Backtests",
            backend_source="api/backtests.py + intelligence_control/",
            frontend_location="/admin/backtests",
            api_route="GET /admin/backtests",
            role_required="operator",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="admin.reports.cockpit",
            title="Reports and briefings",
            category="Command Center",
            backend_source="intelligence_control/service.py + api/reports.py",
            frontend_location="/admin/reports",
            api_route="GET /admin/reports",
            role_required="operator",
            viewable=True,
            controllable=True,
            priority="High",
        ),
        _entry(
            id="costs.budget.patch",
            title="Edit cost budgets",
            category="Costs",
            backend_source="intelligence_control/repository.py",
            frontend_location="/admin/costs",
            api_route="PATCH /admin/costs/budgets",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
        ),
        _entry(
            id="costs.kill_switch",
            title="Cost kill switch",
            category="Costs",
            backend_source="intelligence_control/service.py",
            frontend_location="/admin/costs",
            api_route="POST /admin/costs/kill-switch",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            kill_switch=True,
            priority="Critical",
        ),
    ]


def _command_console() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.commands.registry",
            title="Command console registry",
            category="MASTER_ADMIN",
            backend_source="command_control/registry.py + api/commands.py",
            frontend_location="/admin/console",
            api_route="GET /admin/commands",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=False,
            audit_implemented=True,
            priority="Critical",
            notes="Allowlisted operator CLI — no arbitrary shell/SQL/systemctl.",
        ),
        _entry(
            id="admin.commands.preview",
            title="Command preview",
            category="MASTER_ADMIN",
            backend_source="command_control/service.py",
            frontend_location="/admin/console",
            api_route="POST /admin/commands/preview",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            audit_implemented=True,
            priority="High",
        ),
        _entry(
            id="admin.commands.run",
            title="Execute allowlisted command",
            category="MASTER_ADMIN",
            backend_source="command_control/executor.py",
            frontend_location="/admin/console",
            api_route="POST /admin/commands/run",
            role_required="MASTER_ADMIN",
            viewable=True,
            controllable=True,
            dangerous=True,
            audit_implemented=True,
            priority="Critical",
            notes="Dispatches only to mapped control-plane APIs.",
        ),
        _entry(
            id="command.edge.routes.check",
            title="EDGE ROUTES CHECK command",
            category="Edge",
            backend_source="command_control/executor.py + edge/service.py",
            frontend_location="/admin/console",
            api_route="POST /admin/commands/run",
            role_required="operator",
            viewable=True,
            controllable=True,
            audit_implemented=True,
            priority="High",
        ),
    ]


def _pipelines_cockpit() -> list[ControlMatrixEntry]:
    return [
        _entry(
            id="admin.pipelines.status",
            title="Data pipeline hub",
            category="Workers/Schedulers",
            backend_source="market_control/service.py + api/pipelines.py",
            frontend_location="/admin/pipelines",
            api_route="GET /admin/pipelines",
            role_required="operator",
            viewable=True,
            controllable=False,
            priority="High",
            notes="Worker run summary + data-ingestion /metrics/state.",
        ),
    ]


def _engine_room_gaps() -> list[ControlMatrixEntry]:
    """Internal capabilities not yet in Terminal — documented gaps."""
    gaps: list[tuple[str, str, str, str, str]] = [
        ("risk.validate-order", "Risk order validation", "Risk", "services/risk_service", "7060"),
        ("compliance.check-order", "Compliance order check", "Legal/Compliance", "services/compliance_service", "7070"),
        ("broker.market-order", "Submit market order", "Broker/Portfolio", "services/broker_adapter_alpaca/app.py", "7090"),
        ("data-api.admin-read", "Data API admin dashboard data", "Data API", "TheEyeBetaDataAPI/app/api/routes/admin.py", "7000"),
        ("data-api.health-public", "Data API public health", "Data API", "TheEyeBetaDataAPI/app/api/routes/health.py", "7000"),
        ("ingest.manual-run", "Manual data ingest", "Market Data", "services/data_ingestion/main.py", "7010"),
        ("audit.nats-consumer", "Audit NATS consumer", "Audit", "services/audit_service/consumer.py", "7110"),
    ]
    rows: list[ControlMatrixEntry] = []
    for key, title, category, src, port in gaps:
        rows.append(
            _entry(
                id=f"gap.{key}",
                title=title,
                category=category,
                backend_source=src,
                service_port_dependency=f"127.0.0.1:{port}",
                viewable=False,
                controllable=False,
                priority="Critical" if "gate" in key or "broker.market" in key else "High",
                frontend_gap="Not exposed in operator Terminal.",
                backend_only_reason=_backend_only_reason(key),
            ),
        )
    return rows


def _backend_only_reason(key: str) -> str | None:
    reasons = {
        "audit.nats-consumer": "JetStream consumer writes hash chain; Terminal reads via audit log + verify.",
        "oms.submission-gate": "Redis-backed gate; requires dedicated Emergency Trading panel.",
        "broker.live-gate": "DB live_approval check; requires Emergency Trading panel.",
    }
    return reasons.get(key)


def build_control_matrix() -> list[ControlMatrixEntry]:
    """Return the full static control matrix."""
    sections = [
        _edge_routes,
        _edge_registry_and_ports,
        _command_center_and_master_admin,
        _admin_pages,
        _dangerous_admin_actions,
        _services_systemd,
        _workers_timers,
        _emergency_trading,
        _risk_cockpit,
        _compliance_cockpit,
        _orders_blotter,
        _broker_blotter,
        _market_data_cockpit,
        _snapshots_cockpit,
        _sector_universe_cockpit,
        _pipelines_cockpit,
        _intelligence_cockpit,
        _command_console,
        _engine_room_gaps,
    ]
    entries: list[ControlMatrixEntry] = []
    for builder in sections:
        entries.extend(builder())
    return entries


def summarize_categories(entries: list[ControlMatrixEntry]) -> list[ControlMatrixCategorySummary]:
    """Aggregate entry counts per category."""
    buckets: dict[str, list[ControlMatrixEntry]] = {}
    for entry in entries:
        buckets.setdefault(entry.category, []).append(entry)

    summaries: list[ControlMatrixCategorySummary] = []
    for category in sorted(buckets.keys()):
        rows = buckets[category]
        summaries.append(
            ControlMatrixCategorySummary(
                category=category,
                total=len(rows),
                viewable=sum(1 for r in rows if r.viewable),
                controllable=sum(1 for r in rows if r.controllable),
                critical_count=sum(1 for r in rows if r.priority == "Critical"),
                gap_count=sum(
                    1 for r in rows if r.backend_gap or r.frontend_gap
                ),
            ),
        )
    return summaries


def build_control_matrix_response() -> ControlMatrixResponse:
    """Build the API response with categories and drift alerts."""
    from control_matrix.staleness import collect_staleness_alerts
    from control_matrix.validation import collect_drift_alerts, validate_matrix_invariants

    entries = build_control_matrix()
    violations = validate_matrix_invariants(entries)
    staleness = collect_staleness_alerts(entries)
    drift = collect_drift_alerts(entries)
    if violations:
        drift = [*drift, *[f"MATRIX INVARIANT: {v}" for v in violations]]
    if staleness:
        drift = [*drift, *staleness]

    return ControlMatrixResponse(
        version=MATRIX_VERSION,
        generated_at=datetime.now(tz=UTC),
        entries=entries,
        categories=summarize_categories(entries),
        drift_alerts=drift,
    )
