# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compliance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'compliance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ompliance.proto\x12\x0fzinc.compliance\"\xa7\x01\n\x16\x43omplianceCheckRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0cportfolio_id\x18\x02 \x01(\t\x12\x15\n\rinstrument_id\x18\x03 \x01(\x03\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x0c\n\x04side\x18\x05 \x01(\t\x12\x0b\n\x03qty\x18\x06 \x01(\x01\x12\x13\n\x0blimit_price\x18\x07 \x01(\x01\x12\x0e\n\x06market\x18\x08 \x01(\t\"c\n\x0bRuleOutcome\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x33\n\x07outcome\x18\x02 \x01(\x0e\x32\".zinc.compliance.ComplianceOutcome\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\xb5\x01\n\x12\x43omplianceDecision\x12\x33\n\x07outcome\x18\x01 \x01(\x0e\x32\".zinc.compliance.ComplianceOutcome\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x32\n\x0crule_results\x18\x03 \x03(\x0b\x32\x1c.zinc.compliance.RuleOutcome\x12\x14\n\x0c\x66\x61iled_rules\x18\x04 \x03(\t\x12\x10\n\x08\x61pproved\x18\x05 \x01(\x08*2\n\x11\x43omplianceOutcome\x12\x08\n\x04PASS\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x42LOCK\x10\x02\x32h\n\nCompliance\x12Z\n\nCheckOrder\x12\'.zinc.compliance.ComplianceCheckRequest\x1a#.zinc.compliance.ComplianceDecisionB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compliance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_COMPLIANCEOUTCOME']._serialized_start=492
  _globals['_COMPLIANCEOUTCOME']._serialized_end=542
  _globals['_COMPLIANCECHECKREQUEST']._serialized_start=38
  _globals['_COMPLIANCECHECKREQUEST']._serialized_end=205
  _globals['_RULEOUTCOME']._serialized_start=207
  _globals['_RULEOUTCOME']._serialized_end=306
  _globals['_COMPLIANCEDECISION']._serialized_start=309
  _globals['_COMPLIANCEDECISION']._serialized_end=490
  _globals['_COMPLIANCE']._serialized_start=544
  _globals['_COMPLIANCE']._serialized_end=648
_builder.BuildServices(DESCRIPTOR, 'compliance_pb2', _globals)
# @@protoc_insertion_point(module_scope)
