# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zinc_proto import compliance_pb2 as compliance__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compliance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplianceStub(object):
    """Pre-trade compliance rule checks (Part 9.2).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOrder = channel.unary_unary(
                '/zinc.compliance.Compliance/CheckOrder',
                request_serializer=compliance__pb2.ComplianceCheckRequest.SerializeToString,
                response_deserializer=compliance__pb2.ComplianceDecision.FromString,
                _registered_method=True)


class ComplianceServicer(object):
    """Pre-trade compliance rule checks (Part 9.2).
    """

    def CheckOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=compliance__pb2.ComplianceCheckRequest.FromString,
                    response_serializer=compliance__pb2.ComplianceDecision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zinc.compliance.Compliance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zinc.compliance.Compliance', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Compliance(object):
    """Pre-trade compliance rule checks (Part 9.2).
    """

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zinc.compliance.Compliance/CheckOrder',
            compliance__pb2.ComplianceCheckRequest.SerializeToString,
            compliance__pb2.ComplianceDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
