# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'guard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguard.proto\x12\nzinc.guard\"<\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03 \x01(\t\"\x9f\x01\n\x0fValidateRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x12\n\nraw_output\x18\x03 \x01(\t\x12(\n\ntool_calls\x18\x04 \x03(\x0b\x32\x14.zinc.guard.ToolCall\x12\x15\n\rsnapshot_json\x18\x05 \x01(\t\x12\x15\n\rvalid_symbols\x18\x06 \x03(\t\"}\n\x10ValidateResponse\x12$\n\x07outcome\x18\x01 \x01(\x0e\x32\x13.zinc.guard.Outcome\x12)\n\nviolations\x18\x02 \x03(\x0b\x32\x15.zinc.guard.Violation\x12\x18\n\x10sanitized_output\x18\x03 \x01(\t\";\n\tViolation\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t*8\n\x07Outcome\x12\x08\n\x04PASS\x10\x00\x12\t\n\x05RETRY\x10\x01\x12\x0c\n\x08\x45SCALATE\x10\x02\x12\n\n\x06REJECT\x10\x03\x32Y\n\x05Guard\x12P\n\x13ValidateAgentOutput\x12\x1b.zinc.guard.ValidateRequest\x1a\x1c.zinc.guard.ValidateResponseB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_OUTCOME']._serialized_start=439
  _globals['_OUTCOME']._serialized_end=495
  _globals['_TOOLCALL']._serialized_start=27
  _globals['_TOOLCALL']._serialized_end=87
  _globals['_VALIDATEREQUEST']._serialized_start=90
  _globals['_VALIDATEREQUEST']._serialized_end=249
  _globals['_VALIDATERESPONSE']._serialized_start=251
  _globals['_VALIDATERESPONSE']._serialized_end=376
  _globals['_VIOLATION']._serialized_start=378
  _globals['_VIOLATION']._serialized_end=437
  _globals['_GUARD']._serialized_start=497
  _globals['_GUARD']._serialized_end=586
_builder.BuildServices(DESCRIPTOR, 'guard_pb2', _globals)
# @@protoc_insertion_point(module_scope)
