# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: risk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'risk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrisk.proto\x12\tzinc.risk\"\xa6\x01\n\x10RiskCheckRequest\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\x12\x15\n\rinstrument_id\x18\x02 \x01(\x03\x12\x0c\n\x04side\x18\x03 \x01(\t\x12\x0b\n\x03qty\x18\x04 \x01(\x01\x12\x13\n\x0blimit_price\x18\x05 \x01(\x01\x12\x14\n\x0corder_intent\x18\x06 \x01(\t\x12\x0e\n\x06sector\x18\x07 \x01(\t\x12\x0f\n\x07\x63luster\x18\x08 \x01(\t\"\xd7\x01\n\x0cRiskDecision\x12\'\n\x07outcome\x18\x01 \x01(\x0e\x32\x16.zinc.risk.RiskOutcome\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x35\n\x07metrics\x18\x03 \x03(\x0b\x32$.zinc.risk.RiskDecision.MetricsEntry\x12\x15\n\rfailed_checks\x18\x04 \x03(\t\x12\x10\n\x08\x61pproved\x18\x05 \x01(\x08\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"(\n\x10PortfolioRequest\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\"\xba\x01\n\x10PortfolioMetrics\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\x12\x0e\n\x06var_95\x18\x02 \x01(\x01\x12\x0f\n\x07\x63var_95\x18\x03 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x04 \x01(\x01\x12\x16\n\x0egross_exposure\x18\x05 \x01(\x01\x12\x14\n\x0cnet_exposure\x18\x06 \x01(\x01\x12\x10\n\x08\x62\x65ta_spy\x18\x07 \x01(\x01\x12\x19\n\x11\x63oncentration_hhi\x18\x08 \x01(\x01*-\n\x0bRiskOutcome\x12\t\n\x05\x41LLOW\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x42LOCK\x10\x02\x32\xa2\x01\n\x04Risk\x12\x45\n\rValidateOrder\x12\x1b.zinc.risk.RiskCheckRequest\x1a\x17.zinc.risk.RiskDecision\x12S\n\x17\x43omputePortfolioMetrics\x12\x1b.zinc.risk.PortfolioRequest\x1a\x1b.zinc.risk.PortfolioMetricsB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_RISKDECISION_METRICSENTRY']._loaded_options = None
  _globals['_RISKDECISION_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_RISKOUTCOME']._serialized_start=643
  _globals['_RISKOUTCOME']._serialized_end=688
  _globals['_RISKCHECKREQUEST']._serialized_start=26
  _globals['_RISKCHECKREQUEST']._serialized_end=192
  _globals['_RISKDECISION']._serialized_start=195
  _globals['_RISKDECISION']._serialized_end=410
  _globals['_RISKDECISION_METRICSENTRY']._serialized_start=364
  _globals['_RISKDECISION_METRICSENTRY']._serialized_end=410
  _globals['_PORTFOLIOREQUEST']._serialized_start=412
  _globals['_PORTFOLIOREQUEST']._serialized_end=452
  _globals['_PORTFOLIOMETRICS']._serialized_start=455
  _globals['_PORTFOLIOMETRICS']._serialized_end=641
  _globals['_RISK']._serialized_start=691
  _globals['_RISK']._serialized_end=853
_builder.BuildServices(DESCRIPTOR, 'risk_pb2', _globals)
# @@protoc_insertion_point(module_scope)
