"""MASTER_ADMIN ownership/control matrix API."""

# ruff: noqa: E501

from __future__ import annotations

from datetime import UTC, datetime

import structlog
from fastapi import APIRouter
from rbac import Role, require_role

from zinc_schemas.admin_dto import (
    MasterAdminControlEntry,
    MasterAdminControlMatrixResponse,
)

log = structlog.get_logger()

router = APIRouter(prefix="/master-admin", tags=["master-admin"])

_DANGEROUS_ACTION_REQUIREMENTS = [
    "explicit confirmation prompt",
    "consequences preview before execution",
    "durable audit_log row with actor, timestamp, reason, override flag, and payload",
    "timestamped action history visible from /admin/audit/log",
    "rollback or compensating action where technically possible",
    "emergency stop or lockout control for trading, schedulers, and external mutating integrations",
]


def _entry(**kwargs: object) -> MasterAdminControlEntry:
    """Keep the static registry compact while still validating every row."""
    return MasterAdminControlEntry(**kwargs)


def build_master_admin_control_matrix() -> list[MasterAdminControlEntry]:
    """Return the backend feature registry from the MASTER_ADMIN point of view."""
    return [
        _entry(
            feature="Command Center / Ops Pulse",
            category="Admin/system control",
            source=[
                "services/admin_service/api/ops.py",
                "services/admin_service/lib/queries/ops.py",
            ],
            frontend_location="/admin/ and future Admin/System Control page",
            viewable=True,
            controllable=False,
            editable=False,
            schedulable=False,
            kill_switch_needed=False,
            confirmation_needed=False,
            role_required="READ_ONLY",
            audit_log_required=False,
            api_exists=True,
            available_actions=[
                "view health",
                "view stale heartbeats",
                "view open breakers",
                "view critical alerts",
            ],
            existing_endpoints=["GET /admin/ops/pulse"],
            missing_backend_work=[
                "Add frontend panel that links every degraded item to its native control endpoint."
            ],
            dangerous_actions=[],
            operator_notes="Aggregates control-plane state but does not itself mutate anything.",
            priority="Critical",
        ),
        _entry(
            feature="Workers and data pipelines",
            category="Data ingestion / processing",
            source=[
                "services/admin_service/api/workers.py",
                "workers/",
                "db/migrations/versions/0020_worker_ops.py",
            ],
            frontend_location="Workers / Schedulers",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="OPERATOR for manual run; MASTER_ADMIN for forced overrides",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "view registry",
                "view run history",
                "trigger manual run",
                "dry run",
                "force run",
            ],
            existing_endpoints=[
                "GET /admin/workers",
                "GET /admin/workers/runs",
                "POST /admin/workers/{name}/run",
            ],
            missing_backend_work=[
                "Add pause/resume/stop endpoints with cooperative worker cancellation.",
                "Persist worker configuration versions and expose PATCH /admin/workers/{name}/config.",
                "Attach full stdout/stderr log artifact storage instead of tail-only response fields.",
                "Expose retry-from-failed-run endpoint bound to a prior run_id.",
            ],
            dangerous_actions=[
                "force run",
                "manual run against production dates",
                "future stop/cancel",
            ],
            operator_notes="Current API can trigger but cannot stop a running subprocess once it has returned control to the worker process.",
            priority="Critical",
        ),
        _entry(
            feature="Systemd timers and schedulers",
            category="Task/job scheduling",
            source=["services/admin_service/api/timers.py", "deploy/systemd/"],
            frontend_location="Workers / Schedulers",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="OPERATOR for trigger; MASTER_ADMIN for schedule changes",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "view active/inactive status",
                "view last trigger",
                "view next trigger",
                "trigger now",
            ],
            existing_endpoints=["GET /admin/timers", "POST /admin/timers/{name}/trigger"],
            missing_backend_work=[
                "Add enable/disable/start/stop/pause/resume endpoints for whitelisted units.",
                "Add schedule editing through reviewed systemd drop-ins or database-backed scheduler config.",
                "Expose journalctl logs and timer failure history by unit.",
            ],
            dangerous_actions=["trigger now", "future disable scheduler", "future edit schedule"],
            operator_notes="Manual trigger exists; schedule mutation is intentionally not exposed until there is a safe unit-editing backend.",
            priority="Critical",
        ),
        _entry(
            feature="Services and first-party processes",
            category="Admin/system control",
            source=["services/admin_service/api/services.py"],
            frontend_location="Observability / Services",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="OPERATOR for restart; MASTER_ADMIN for stop/disable",
            audit_log_required=True,
            api_exists=True,
            available_actions=["view systemd state", "restart whitelisted services"],
            existing_endpoints=[
                "GET /admin/services/status",
                "POST /admin/services/{name}/restart",
            ],
            missing_backend_work=[
                "Add stop/start/disable/enable endpoints for MASTER_ADMIN with sudoers allowlist.",
                "Expose service logs, restart history, and failed unit diagnostics.",
                "Expand whitelist or explicitly mark infrastructure units as backend-only.",
            ],
            dangerous_actions=["restart service", "future stop service", "future disable service"],
            operator_notes="Current restart whitelist is deliberately narrow; infrastructure process control is not exposed.",
            priority="Critical",
        ),
        _entry(
            feature="Trading live approval and emergency halt",
            category="Trading function / emergency control",
            source=["services/admin_service/api/trading.py", "services/broker_adapter_alpaca/"],
            frontend_location="Trading / Emergency Controls",
            viewable=True,
            controllable=True,
            editable=True,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="MASTER_ADMIN",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "issue confirmation token",
                "enable live trading",
                "disable live trading",
                "emergency halt",
            ],
            existing_endpoints=[
                "GET /admin/trading/live-approval/token",
                "POST /admin/trading/live-approval",
                "POST /admin/trading/emergency-halt",
            ],
            missing_backend_work=[
                "Add frontend emergency halt panel with consequence preview and post-action audit trail.",
                "Add resume-from-emergency-halt workflow with explicit checks and audit.",
                "Show current Redis halt/live gate state in read API.",
            ],
            dangerous_actions=["enable live trading", "disable live trading", "emergency halt"],
            operator_notes="Override is allowed only with token + consequence acknowledgement, and every override is audited.",
            priority="Critical",
        ),
        _entry(
            feature="Orders, OMS, broker, positions, reconciliation",
            category="Portfolio/account logic / trading function",
            source=[
                "services/admin_service/api/orders.py",
                "services/admin_service/api/oms.py",
                "services/admin_service/api/broker.py",
                "services/oms/",
                "services/broker_adapter_alpaca/",
            ],
            frontend_location="Orders / Portfolio / Broker / OMS",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="OPERATOR for order approval; MASTER_ADMIN for reconciliation override",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "view pending orders",
                "approve/reject orders",
                "view broker status",
                "view broker positions",
                "view/resolve reconciliation",
            ],
            existing_endpoints=[
                "GET /admin/orders/pending",
                "GET /admin/orders/{id}",
                "POST /admin/orders/{id}/approve",
                "POST /admin/orders/{id}/reject",
                "GET /admin/broker/status",
                "GET /admin/broker/positions",
                "GET /admin/oms/reconciliation",
                "POST /admin/oms/reconciliation/resolve",
            ],
            missing_backend_work=[
                "Add cancel/replace order APIs if OMS supports them.",
                "Add broker order/fill history proxy and frontend blotter.",
                "Require consequence acknowledgement on OMS reconciliation resolve.",
            ],
            dangerous_actions=[
                "approve order",
                "resolve reconciliation drift",
                "future cancel/replace live order",
            ],
            operator_notes="Live broker/OMS power depends on currently deployed downstream services.",
            priority="Critical",
        ),
        _entry(
            feature="Risk service and risk metrics",
            category="Risk calculation",
            source=[
                "services/admin_service/api/risk.py",
                "services/risk_service/",
                "scripts/risk_metrics_refresh.py",
            ],
            frontend_location="Risk",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=True,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="ANALYST read; OPERATOR compute; MASTER_ADMIN override",
            audit_log_required=True,
            api_exists=True,
            available_actions=["view risk metrics", "trigger compute"],
            existing_endpoints=["GET /admin/risk/metrics", "POST /admin/risk/compute"],
            missing_backend_work=[
                "Add risk limit configuration CRUD with versioned approvals.",
                "Add risk override endpoint that requires MASTER_ADMIN and records override payload.",
                "Expose risk-service logs, inputs, outputs, and failed validation history.",
            ],
            dangerous_actions=["manual risk compute", "future risk-limit override"],
            operator_notes="Risk controls exist as compute/read endpoints, not as a full limit-management control plane.",
            priority="Critical",
        ),
        _entry(
            feature="Compliance checks and legal controls",
            category="Legal/compliance/audit",
            source=["services/admin_service/api/compliance.py", "services/compliance_service/"],
            frontend_location="Legal / Compliance",
            viewable=True,
            controllable=False,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=False,
            role_required="COMPLIANCE",
            audit_log_required=True,
            api_exists=True,
            available_actions=["view recent compliance checks"],
            existing_endpoints=["GET /admin/compliance/checks"],
            missing_backend_work=[
                "Add restricted-list, mandate, PDT, AML, and wash-sale rule configuration endpoints.",
                "Add manual re-check/override endpoints requiring MASTER_ADMIN plus compliance audit payload.",
                "Add frontend legal hold/lock controls for non-admin use.",
            ],
            dangerous_actions=["future compliance override", "future restricted-list edit"],
            operator_notes="The current frontend can observe compliance outcomes but cannot administer compliance policy.",
            priority="Critical",
        ),
        _entry(
            feature="Audit log, hash chain, checkpoints, alerts",
            category="Legal/compliance/audit",
            source=[
                "services/admin_service/api/audit.py",
                "services/admin_service/api/alerts.py",
                "services/audit_service/",
                "db/migrations/versions/0009_audit.py",
            ],
            frontend_location="Audit / Alerts",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=False,
            confirmation_needed=True,
            role_required="COMPLIANCE for read; MASTER_ADMIN for chain-affecting controls",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "view audit log",
                "verify chain",
                "view checkpoints",
                "view/ack alerts",
            ],
            existing_endpoints=[
                "GET /admin/audit/log",
                "GET /admin/audit/verify",
                "GET /admin/audit/checkpoints",
                "GET /admin/alerts",
                "POST /admin/alerts/{id}/ack",
            ],
            missing_backend_work=[
                "Add immutable export endpoint and checkpoint creation endpoint if operations require manual checkpointing.",
                "Add alert assignment/escalation controls and audit them.",
            ],
            dangerous_actions=["ack critical alert", "future manual checkpoint"],
            operator_notes="Audit mutation is deliberately restricted; SQL write API also blocks audit/proposal table writes.",
            priority="Critical",
        ),
        _entry(
            feature="Agents, constitutions, guard violations, proposals",
            category="Agent/automation logic",
            source=[
                "services/admin_service/api/agents.py",
                "services/admin_service/api/guard.py",
                "services/admin_service/api/proposals.py",
                "agents/",
            ],
            frontend_location="Agents / Violations / Proposals",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="OPERATOR for run/resolve/review; MASTER_ADMIN for future disable/lock",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "view agents",
                "view runs",
                "view constitution",
                "run agent",
                "view/resolve violations",
                "approve/reject proposals",
            ],
            existing_endpoints=[
                "GET /admin/agents",
                "GET /admin/agents/{id}/runs",
                "GET /admin/agents/{id}/constitution",
                "POST /admin/agents/{id}/run",
                "GET /admin/guard/violations",
                "POST /admin/guard/violations/{id}/resolve",
                "GET /admin/proposals",
                "POST /admin/proposals/{id}/approve",
                "POST /admin/proposals/{id}/reject",
            ],
            missing_backend_work=[
                "Add agent pause/disable/lock endpoint.",
                "Add constitution/config editor with version history and rollback.",
                "Add proposal rollback or supersede endpoint.",
            ],
            dangerous_actions=[
                "run agent",
                "resolve violation",
                "approve proposal",
                "future edit constitution",
            ],
            operator_notes="Agent visibility is good; lifecycle controls are incomplete.",
            priority="High",
        ),
        _entry(
            feature="Backtests, validation runs, reports, briefings",
            category="Reporting/exporting / market analysis",
            source=[
                "services/admin_service/api/backtest.py",
                "services/admin_service/api/briefings.py",
                "services/backtest_engine/",
            ],
            frontend_location="Backtests / Reports / Briefings",
            viewable=True,
            controllable=True,
            editable=False,
            schedulable=False,
            kill_switch_needed=False,
            confirmation_needed=True,
            role_required="ANALYST read; OPERATOR start",
            audit_log_required=True,
            api_exists=True,
            available_actions=[
                "view backtest runs",
                "start backtest",
                "view results",
                "view briefings",
            ],
            existing_endpoints=[
                "GET /admin/backtest",
                "POST /admin/backtest",
                "GET /admin/backtest/{id}/results",
                "GET /admin/briefings",
            ],
            missing_backend_work=[
                "Add cancel/retry backtest endpoint.",
                "Add report export registry and generated artifact browser.",
                "Expose backtest-engine logs and input parameter snapshots.",
            ],
            dangerous_actions=["start expensive backtest", "future cancel validation run"],
            operator_notes="Backtest start is auditable but not fully lifecycle-managed.",
            priority="High",
        ),
        _entry(
            feature="SQL and database operations",
            category="Database/storage / security-sensitive operation",
            source=["services/admin_service/api/sql.py"],
            frontend_location="SQL / Command Console",
            viewable=True,
            controllable=True,
            editable=True,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="ANALYST for SELECT; MASTER_ADMIN for write SQL",
            audit_log_required=True,
            api_exists=True,
            available_actions=["read-only query", "confirmed write SQL"],
            existing_endpoints=["POST /admin/sql/query", "POST /admin/sql/execute"],
            missing_backend_work=[
                "Add rollback helper for migrations/known reversible operations.",
                "Add dry-run/explain endpoint for write statements where possible.",
                "Add permission assignment UI instead of using SQL for admin RBAC changes.",
            ],
            dangerous_actions=["write SQL", "manual data repair", "configuration mutation"],
            operator_notes="This is the broadest override path. It is MASTER_ADMIN-only and records every execution.",
            priority="Critical",
        ),
        _entry(
            feature="Users, permissions, RBAC",
            category="Authentication/authorization",
            source=[
                "services/admin_service/auth.py",
                "services/admin_service/rbac.py",
                "db/migrations/versions/0026_admin_rbac.py",
            ],
            frontend_location="Users / Permissions",
            viewable=False,
            controllable=False,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="MASTER_ADMIN",
            audit_log_required=True,
            api_exists=False,
            available_actions=[
                "bootstrap user via script/env",
                "enforce role claims at route layer",
            ],
            existing_endpoints=[
                "POST /admin/auth/login",
                "POST /admin/auth/refresh",
                "POST /admin/auth/logout",
            ],
            missing_backend_work=[
                "Add admin user list/detail/create/disable endpoints.",
                "Add role assignment/revocation endpoints with dual-confirm and audit.",
                "Add session revocation and account lock endpoints.",
                "Add frontend Users / Permissions page.",
            ],
            dangerous_actions=["grant MASTER_ADMIN", "disable user", "revoke sessions"],
            operator_notes="Route RBAC exists, but RBAC administration is not yet exposed safely.",
            priority="Critical",
        ),
        _entry(
            feature="External integrations and secrets",
            category="External integrations / configuration",
            source=[
                "services/data_ingestion/src/data_ingestion/adapters/",
                "services/broker_adapter_alpaca/",
                "config/",
                "secrets/",
                "tb/tb/commands/secrets.py",
            ],
            frontend_location="Settings / Integrations",
            viewable=False,
            controllable=False,
            editable=False,
            schedulable=False,
            kill_switch_needed=True,
            confirmation_needed=True,
            role_required="MASTER_ADMIN",
            audit_log_required=True,
            api_exists=False,
            available_actions=["CLI-only secret workflows", "service-specific health checks"],
            existing_endpoints=[],
            missing_backend_work=[
                "Add redacted integration status endpoint per provider.",
                "Add safe config editor for non-secret routing/settings with version history.",
                "Keep raw secret material backend-only; expose rotate/test workflows that never reveal values.",
                "Audit every integration enable/disable/test/rotate action.",
            ],
            dangerous_actions=[
                "rotate credentials",
                "disable broker/data vendor",
                "change LLM routing",
            ],
            operator_notes="Raw secrets should not be frontend-readable even for MASTER_ADMIN; owner control should be via rotate/test/disable workflows.",
            priority="High",
        ),
    ]


def register_master_admin_routes() -> APIRouter:
    """Attach MASTER_ADMIN registry handlers."""

    @router.get(
        "/control-matrix",
        response_model=MasterAdminControlMatrixResponse,
        summary="MASTER_ADMIN backend control matrix (MASTER_ADMIN)",
    )
    async def control_matrix(
        user: dict[str, str] = require_role(Role.MASTER_ADMIN),
    ) -> MasterAdminControlMatrixResponse:
        """Return the feature-by-feature system-owner control contract."""
        controls = build_master_admin_control_matrix()
        gaps = [
            entry
            for entry in controls
            if (not entry.api_exists) or entry.missing_backend_work or not entry.controllable
        ]
        log.info(
            "admin_master_control_matrix",
            controls=len(controls),
            gaps=len(gaps),
            sub=user["sub"],
        )
        return MasterAdminControlMatrixResponse(
            role="MASTER_ADMIN",
            authority="system_owner_operator",
            generated_at=datetime.now(tz=UTC),
            controls=controls,
            gaps=gaps,
            dangerous_actions_require=_DANGEROUS_ACTION_REQUIREMENTS,
        )

    return router
