// Generated from ../docs/frontend/openapi.json. Do not edit by hand.
export const OPENAPI_VERSION = "3.1.0";
export const OPENAPI_TITLE = "TheEyeBetaDataAPI";
export const OPENAPI_PATHS = [
  "/",
  "/api/v1/admin/audit-events",
  "/api/v1/admin/dashboard",
  "/api/v1/admin/dashboard-data",
  "/api/v1/admin/engine-status",
  "/api/v1/admin/etl-jobs",
  "/api/v1/admin/named-query",
  "/api/v1/admin/price-ticks/{ticker}",
  "/api/v1/admin/queries",
  "/api/v1/admin/worker-heartbeats",
  "/api/v1/advisor/chat",
  "/api/v1/advisor/context",
  "/api/v1/analytics/snapshots/{ticker}",
  "/api/v1/auth/service-token",
  "/api/v1/chat",
  "/api/v1/context",
  "/api/v1/data/tables",
  "/api/v1/data/tables/{table}/columns",
  "/api/v1/data/tables/{table}/rows",
  "/api/v1/financials/{ticker}/balance",
  "/api/v1/financials/{ticker}/cashflow",
  "/api/v1/financials/{ticker}/income",
  "/api/v1/financials/{ticker}/quality",
  "/api/v1/indicators/{ticker}/returns",
  "/api/v1/indicators/{ticker}/risk",
  "/api/v1/indicators/{ticker}/technical",
  "/api/v1/indicators/{ticker}/valuation",
  "/api/v1/market-data/quotes",
  "/api/v1/news/market",
  "/api/v1/news/ticker/{ticker}",
  "/api/v1/portfolio/state",
  "/api/v1/reference/calendar",
  "/api/v1/reference/countries",
  "/api/v1/reference/currencies",
  "/api/v1/reference/exchanges",
  "/api/v1/reference/industries",
  "/api/v1/reference/sectors",
  "/api/v1/signals/latest",
  "/api/v1/symbols/search",
  "/api/v1/tickers/{ticker}",
  "/api/v1/tickers/{ticker}/corporate-actions",
  "/api/v1/tickers/{ticker}/fundamentals",
  "/api/v1/tickers/{ticker}/price-history",
  "/health",
  "/v1/macro/latest",
  "/v1/macro/regime",
  "/v1/macro/series",
  "/v1/macro/series/{code}"
] as const;
export type OpenApiPath = (typeof OPENAPI_PATHS)[number];
