"""Read-only diagnostic: maps every schema/table/hypertable relationship.

Writes docs/db-state-map.md and also prints to stdout.
NO mutations of any kind.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import psycopg
from dotenv import load_dotenv

load_dotenv()

_raw_url = os.environ.get("DATABASE_URL", "")
DATABASE_URL: str = re.sub(r"\+\w+", "", _raw_url, count=1)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = REPO_ROOT / "docs" / "db-state-map.md"


# ── helpers ───────────────────────────────────────────────────────────────────

class Report:
    """Accumulate markdown lines, print immediately, write file at end."""

    def __init__(self) -> None:
        self._lines: list[str] = []

    def line(self, text: str = "") -> None:
        print(text, flush=True)
        self._lines.append(text)

    def h(self, level: int, text: str) -> None:
        prefix = "#" * level
        self.line(f"{prefix} {text}")

    def table(self, headers: list[str], rows: list[list[Any]]) -> None:
        """Emit a GitHub-flavoured markdown table."""
        widths = [max(len(str(h)), max((len(str(r[i])) for r in rows), default=0))
                  for i, h in enumerate(headers)]
        sep = "| " + " | ".join("-" * w for w, _ in zip(widths, headers)) + " |"
        hdr = "| " + " | ".join(str(h).ljust(w) for w, h in zip(widths, headers)) + " |"
        self.line(hdr)
        self.line(sep)
        for row in rows:
            self.line("| " + " | ".join(str(c).ljust(w) for w, c in zip(widths, row)) + " |")

    def code(self, text: str, lang: str = "") -> None:
        self.line(f"```{lang}")
        for ln in text.splitlines():
            self.line(ln)
        self.line("```")

    def save(self) -> None:
        OUT_FILE.write_text("\n".join(self._lines) + "\n", encoding="utf-8")
        print(f"\n(Report written to {OUT_FILE})", flush=True)


def _conn() -> psycopg.Connection[Any]:
    if not DATABASE_URL:
        print("ERROR: DATABASE_URL not set", file=sys.stderr)
        sys.exit(1)
    return psycopg.connect(DATABASE_URL, autocommit=True)


def _fmt_null(v: Any) -> str:
    if v is None:
        return "NULL"
    return str(v)


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rpt = Report()
    rpt.line("# theeyebeta — Database State Map")
    rpt.line()
    rpt.line("> **Read-only diagnostic.** Generated by `scripts/diagnose_db_state.py`.")
    rpt.line()

    with _conn() as conn:

        # ─── 1. Schemas present ───────────────────────────────────────────────
        rpt.line("---")
        rpt.h(2, "1. Schemas present")
        rpt.line()
        rows = conn.execute(
            """
            SELECT
                n.nspname,
                pg_size_pretty(coalesce(sum(pg_relation_size(c.oid)), 0)) AS size,
                count(*) FILTER (WHERE c.relkind = 'r')  AS tables,
                count(*) FILTER (WHERE c.relkind = 'v')  AS views,
                count(*) FILTER (WHERE c.relkind = 'p')  AS partitioned_tables
            FROM pg_namespace n
            LEFT JOIN pg_class c ON c.relnamespace = n.oid
            WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
            GROUP BY n.nspname
            ORDER BY n.nspname
            """
        ).fetchall()
        rpt.table(
            ["schema", "size", "tables", "views", "partitioned_tables"],
            [[r[0], r[1], r[2], r[3], r[4]] for r in rows],
        )
        rpt.line()

        # ─── 2. All tables in PUBLIC ──────────────────────────────────────────
        rpt.line("---")
        rpt.h(2, "2. All tables in public schema")
        rpt.line()
        rows = conn.execute(
            """
            SELECT
                c.relname,
                c.reltuples::bigint             AS estimated_rows,
                pg_size_pretty(pg_relation_size(c.oid)) AS size,
                coalesce(obj_description(c.oid), '') AS comment
            FROM pg_class c
            JOIN pg_namespace n ON c.relnamespace = n.oid
            WHERE n.nspname = 'public'
              AND c.relkind IN ('r', 'p')
            ORDER BY c.reltuples DESC
            """
        ).fetchall()
        if rows:
            rpt.table(
                ["table", "est_rows", "size", "comment"],
                [[r[0], r[1], r[2], r[3]] for r in rows],
            )
        else:
            rpt.line("_No base tables in public schema._")
        rpt.line()

        # ─── 3. Both alembic_version tables ──────────────────────────────────
        rpt.line("---")
        rpt.h(2, "3. Both alembic_version tables")
        rpt.line()

        # Content
        rows = conn.execute(
            """
            SELECT 'public.alembic_version'     AS source, version_num::text AS version_num
              FROM public.alembic_version
            UNION ALL
            SELECT 'theeyebeta.alembic_version', version_num::text
              FROM theeyebeta.alembic_version
            ORDER BY source
            """
        ).fetchall()
        rpt.table(["source", "version_num"], [[r[0], r[1]] for r in rows])
        rpt.line()

        # Column structure of each
        for schema in ("public", "theeyebeta"):
            rpt.line(f"**{schema}.alembic_version columns:**")
            rpt.line()
            col_rows = conn.execute(
                """
                SELECT column_name, data_type,
                       character_maximum_length,
                       is_nullable, column_default
                FROM information_schema.columns
                WHERE table_schema = %s AND table_name = 'alembic_version'
                ORDER BY ordinal_position
                """,
                (schema,),
            ).fetchall()
            if col_rows:
                rpt.table(
                    ["column", "data_type", "max_len", "nullable", "default"],
                    [[r[0], r[1], _fmt_null(r[2]), r[3], _fmt_null(r[4])] for r in col_rows],
                )
            else:
                rpt.line(f"_`{schema}.alembic_version` does not exist._")
            rpt.line()

        # ─── 4. Side-by-side schema for every name collision ─────────────────
        rpt.line("---")
        rpt.h(2, "4. Column schema for every name collision (public vs theeyebeta)")
        rpt.line()

        # Discover all name collisions
        collision_rows = conn.execute(
            """
            SELECT p.table_name
            FROM information_schema.tables p
            JOIN information_schema.tables t
              ON p.table_name = t.table_name
            WHERE p.table_schema = 'public'
              AND t.table_schema = 'theeyebeta'
              AND p.table_type IN ('BASE TABLE', 'VIEW')
              AND t.table_type IN ('BASE TABLE', 'VIEW')
            ORDER BY p.table_name
            """
        ).fetchall()
        collision_names = [r[0] for r in collision_rows]
        rpt.line(f"**Colliding names ({len(collision_names)}):** "
                 + (", ".join(f"`{n}`" for n in collision_names) or "_none_"))
        rpt.line()

        for name in collision_names:
            rpt.h(3, f"Collision: `{name}`")
            rpt.line()
            for schema in ("public", "theeyebeta"):
                rpt.line(f"**`{schema}.{name}`**")
                rpt.line()
                col_rows = conn.execute(
                    """
                    SELECT ordinal_position, column_name, data_type, udt_name,
                           character_maximum_length, numeric_precision,
                           is_nullable, column_default
                    FROM information_schema.columns
                    WHERE table_schema = %s AND table_name = %s
                    ORDER BY ordinal_position
                    """,
                    (schema, name),
                ).fetchall()
                if col_rows:
                    rpt.table(
                        ["pos", "column", "data_type", "udt", "max_len",
                         "num_prec", "nullable", "default"],
                        [[r[0], r[1], r[2], r[3], _fmt_null(r[4]),
                          _fmt_null(r[5]), r[6], _fmt_null(r[7])]
                         for r in col_rows],
                    )
                else:
                    rpt.line(f"_No columns found for `{schema}.{name}`._")
                rpt.line()

            # Are the schemas identical?
            pub_cols = conn.execute(
                "SELECT column_name, data_type, is_nullable FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name=%s ORDER BY column_name",
                (name,),
            ).fetchall()
            teb_cols = conn.execute(
                "SELECT column_name, data_type, is_nullable FROM information_schema.columns "
                "WHERE table_schema='theeyebeta' AND table_name=%s ORDER BY column_name",
                (name,),
            ).fetchall()
            identical = pub_cols == teb_cols
            rpt.line(f"> Schema match: **{'IDENTICAL ✓' if identical else 'DIFFERENT ✗'}**")
            if not identical:
                pub_set = {r[0] for r in pub_cols}
                teb_set = {r[0] for r in teb_cols}
                only_pub = sorted(pub_set - teb_set)
                only_teb = sorted(teb_set - pub_set)
                if only_pub:
                    rpt.line(f"> Only in public: {only_pub}")
                if only_teb:
                    rpt.line(f"> Only in theeyebeta: {only_teb}")
            rpt.line()

        # ─── 5. Hypertables across both schemas ───────────────────────────────
        rpt.line("---")
        rpt.h(2, "5. Hypertables across all schemas")
        rpt.line()
        rows = conn.execute(
            """
            SELECT
                h.hypertable_schema,
                h.hypertable_name,
                h.num_chunks,
                h.num_dimensions,
                pg_size_pretty(
                    hypertable_size(
                        format('%I.%I', h.hypertable_schema, h.hypertable_name)::regclass
                    )
                ) AS total_size
            FROM timescaledb_information.hypertables h
            ORDER BY h.hypertable_schema, h.hypertable_name
            """
        ).fetchall()
        if rows:
            rpt.table(
                ["schema", "hypertable", "chunks", "dims", "total_size"],
                [[r[0], r[1], r[2], r[3], r[4]] for r in rows],
            )
        else:
            rpt.line("_No hypertables found._")
        rpt.line()

        # ─── 6. Foreign keys crossing schemas ────────────────────────────────
        rpt.line("---")
        rpt.h(2, "6. Foreign keys crossing schemas (public ↔ theeyebeta)")
        rpt.line()
        rows = conn.execute(
            """
            SELECT
                tc.table_schema  || '.' || tc.table_name  AS from_table,
                kcu.column_name                           AS from_col,
                ccu.table_schema || '.' || ccu.table_name AS to_table,
                ccu.column_name                           AS to_col,
                tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              USING (constraint_schema, constraint_name)
            JOIN information_schema.constraint_column_usage ccu
              USING (constraint_schema, constraint_name)
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema  <> ccu.table_schema
              AND tc.table_schema  IN ('public', 'theeyebeta')
              AND ccu.table_schema IN ('public', 'theeyebeta')
            ORDER BY from_table, from_col
            """
        ).fetchall()
        if rows:
            rpt.table(
                ["from_table", "from_col", "to_table", "to_col", "constraint"],
                [[r[0], r[1], r[2], r[3], r[4]] for r in rows],
            )
        else:
            rpt.line("_No cross-schema foreign keys between public and theeyebeta._")
        rpt.line()

        # ─── 7. Active connections ────────────────────────────────────────────
        rpt.line("---")
        rpt.h(2, "7. Active connections (non-idle) right now")
        rpt.line()
        rows = conn.execute(
            """
            SELECT
                pid,
                usename,
                application_name,
                coalesce(client_addr::text, 'local') AS client_addr,
                state,
                backend_start::text,
                query_start::text,
                left(query, 200)                    AS recent_query
            FROM pg_stat_activity
            WHERE datname = 'TheEyeBeta2025Live'
              AND state != 'idle'
              AND pid != pg_backend_pid()
            ORDER BY backend_start
            """
        ).fetchall()
        if rows:
            rpt.table(
                ["pid", "user", "app", "client", "state",
                 "backend_start", "query_start", "recent_query"],
                [[r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7]] for r in rows],
            )
        else:
            rpt.line("_No non-idle connections at query time (other than this script)._")
        rpt.line()

        # Also show all connections (idle too) for app_name breakdown
        rpt.line("**All connections by user/app (including idle):**")
        rpt.line()
        rows = conn.execute(
            """
            SELECT usename, application_name,
                   coalesce(client_addr::text,'local') AS client_addr,
                   count(*) AS conn_count,
                   count(*) FILTER (WHERE state != 'idle') AS active
            FROM pg_stat_activity
            WHERE datname = 'TheEyeBeta2025Live'
              AND pid != pg_backend_pid()
            GROUP BY usename, application_name, client_addr
            ORDER BY conn_count DESC
            """
        ).fetchall()
        if rows:
            rpt.table(
                ["user", "app", "client", "total_conns", "active"],
                [[r[0], r[1], r[2], r[3], r[4]] for r in rows],
            )
        rpt.line()

        # ─── 8. Recent write activity ─────────────────────────────────────────
        rpt.line("---")
        rpt.h(2, "8. Recent write activity per table (top 30 by inserts)")
        rpt.line()
        rows = conn.execute(
            """
            SELECT
                schemaname,
                relname,
                n_tup_ins,
                n_tup_upd,
                n_tup_del,
                n_live_tup,
                coalesce(last_autoanalyze::text, last_analyze::text, 'never') AS last_analyzed
            FROM pg_stat_user_tables
            WHERE schemaname IN ('public', 'theeyebeta')
            ORDER BY n_tup_ins DESC
            LIMIT 30
            """
        ).fetchall()
        if rows:
            rpt.table(
                ["schema", "table", "inserts", "updates", "deletes",
                 "live_rows", "last_analyzed"],
                [[r[0], r[1], r[2], r[3], r[4], r[5], r[6]] for r in rows],
            )
        else:
            rpt.line("_No write-activity data found._")
        rpt.line()

    # ─── 9. Find the other alembic.ini ───────────────────────────────────────
    rpt.line("---")
    rpt.h(2, "9. Locate the other Alembic project (alembic.ini search)")
    rpt.line()

    # Search in likely locations first to avoid scanning the whole filesystem
    search_dirs = [
        "/home/the-eye-beta",
        "/opt",
        "/srv",
        "/var",
        "/root",
        "/usr/local",
        "/app",
    ]
    our_ini = str(REPO_ROOT / "db" / "alembic.ini")

    found_inis: list[str] = []
    for d in search_dirs:
        try:
            result = subprocess.run(
                ["find", d, "-name", "alembic.ini", "-not", "-path", "*/\\.git/*",
                 "-not", "-path", "*/__pycache__/*", "-not", "-path", "*/node_modules/*"],
                capture_output=True, text=True, timeout=15,
            )
            for ln in result.stdout.splitlines():
                p = ln.strip()
                if p and p not in found_inis:
                    found_inis.append(p)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

    if not found_inis:
        rpt.line("_No `alembic.ini` files found in the searched directories._")
    else:
        rpt.line(f"Found **{len(found_inis)}** `alembic.ini` file(s):")
        rpt.line()
        for ini_path in found_inis:
            is_ours = ini_path == our_ini
            rpt.line(f"### `{ini_path}`{'  ← **this repo**' if is_ours else ''}")
            rpt.line()
            try:
                content = Path(ini_path).read_text(encoding="utf-8", errors="replace")
                # Extract key lines only
                url_line = next(
                    (ln for ln in content.splitlines() if ln.strip().startswith("sqlalchemy.url")),
                    "(sqlalchemy.url not found)",
                )
                loc_line = next(
                    (ln for ln in content.splitlines() if ln.strip().startswith("script_location")),
                    "(script_location not found)",
                )
                vt_line = next(
                    (ln for ln in content.splitlines()
                     if "version_table" in ln and not ln.strip().startswith("#")),
                    "(version_table* not set — defaults to public.alembic_version)",
                )
                rpt.code(
                    f"sqlalchemy.url   = {url_line.split('=',1)[-1].strip()}\n"
                    f"script_location  = {loc_line.split('=',1)[-1].strip()}\n"
                    f"version_table    = {vt_line.strip()}"
                )
            except Exception as exc:
                rpt.line(f"_Could not read: {exc}_")
            rpt.line()

    # ─── 10. Recommendations ─────────────────────────────────────────────────
    rpt.line("---")
    rpt.h(2, "10. Recommendations (read-only analysis — no actions taken)")
    rpt.line()
    rpt.line("""
The diagnostics above reveal two independent systems sharing this PostgreSQL database:

**System A — theeyebeta** (`theeyebeta` schema)
- Migration chain: `0000_extensions` → `0009_audit` (conventional slug IDs)
- Managed by `db/alembic.ini` with `version_table_schema = theeyebeta`
- Contains the full platform schema (32 tables + hypertables + partitions)

**System B — unknown project** (`public` schema)
- Migration chain keyed by revision `20260313_02` (date-based IDs → different
  Alembic project or different `file_template`)
- Contains `exchanges` (4 rows), `corporate_actions` (7 833 rows),
  `signals` (~144 M rows), and `alembic_version`
- `signals` is actively receiving writes (144 M rows, count query ran for 500+ s)
  — this is a live, production data stream

**Are the schemas identical or independent?**
- See Section 4 above for the column-by-column comparison.
- If schemas differ, the two `signals` tables are independent systems
  and must not be merged without careful data migration.
- If schemas are identical, the data in `public.signals` should ultimately
  be moved to `theeyebeta.signals` (the hypertable), but only after the
  writing service is reconfigured to use the correct search_path.

**Who is writing?**
- See Sections 7 and 8.  If `pg_stat_activity` shows active inserts into
  `public.signals`, the offending service connection must be fixed
  (set `search_path=theeyebeta,public` on the role or connection string)
  *before* any schema consolidation.

**Safest next moves (in order):**
1. Identify the service writing to `public.signals` (Section 7 / 8 above).
2. Fix its connection to set `search_path=theeyebeta,public`.
3. Verify writes land in `theeyebeta.signals` after the fix.
4. Schedule a back-fill: migrate historical rows from `public.signals` →
   `theeyebeta.signals` (INSERT … ON CONFLICT DO NOTHING in batches).
5. Only after (3) + (4) + zero new writes to public, run the cleanup.
6. The `public.exchanges` (4 rows) and `public.corporate_actions` (7 833 rows)
   need the same treatment — identify origin, reconcile, then drop.

**Awaiting decision before any mutation.**
""".strip())
    rpt.line()

    rpt.save()


if __name__ == "__main__":
    main()
